#!/bin/bash

set -e

BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

install_with_tmp() {
  local name=$1
  local url=$2
  local filename=$3
  SRC_DIR="$(mktemp -d /tmp/tmp-src-XXXXXX)"
  echo "[*] Installing $name from $url..."
  curl -sL "$url" -o "$SRC_DIR/$filename"
  chmod +x "$SRC_DIR/$filename"
  cp "$SRC_DIR/$filename" "$BIN_DIR/$name"
  rm -rf "$SRC_DIR"
  echo "[✓] Installed $name"
}

# 0trace
SRC_DIR="$(mktemp -d /tmp/tmp-src-XXXXXX)"
echo "[*] Downloading 0trace files to $SRC_DIR..."
curl -sL "https://gitlab.com/kalilinux/packages/0trace/-/raw/kali/master/0trace.sh?ref_type=heads" -o "$SRC_DIR/0trace.sh"
curl -sL "https://gitlab.com/kalilinux/packages/0trace/-/raw/kali/master/sendprobe.c?ref_type=heads" -o "$SRC_DIR/sendprobe.c"
curl -sL "https://gitlab.com/kalilinux/packages/0trace/-/raw/kali/master/types.h?ref_type=heads" -o "$SRC_DIR/types.h"
echo "[*] Making 0trace.sh executable..."
chmod +x "$SRC_DIR/0trace.sh"
echo "[*] Compiling sendprobe..."
gcc -o "$SRC_DIR/sendprobe" "$SRC_DIR/sendprobe.c"
echo "[*] Installing 0trace.sh and sendprobe to $BIN_DIR..."
cp "$SRC_DIR/0trace.sh" "$BIN_DIR/0trace"
cp "$SRC_DIR/sendprobe" "$BIN_DIR/sendprobe"
echo "[*] Cleaning up..."
rm -rf "$SRC_DIR"
echo "[✓] Installed 0trace successfully."

# aadict
pip install aadict

# aardwolf
pip install aardwolf

# above
git clone https://gitlab.com/kalilinux/packages/above.git
cd above
pip install .
cd && rm -rf above

# acccheck
install_with_tmp "acccheck" "https://raw.githubusercontent.com/qashqao/acccheck/refs/heads/master/acccheck.pl" "acccheck.pl"

# acstore
pip install acstore

# aesedb
pip install aesedb

# aiocmd
pip install aiocmd

# aioconsole
pip install aioconsole

# aiohttp-apispec
pip install aiohttp-apispec

# aiomultiprocess
pip install aiomultiprocess

# aiosmb
pip install aiosmb

# aiowinreg
pip install aiowinreg

# airgeddon
sudo pacman -Sy base-devel libnl openssl ethtool util-linux zlib libpcap sqlite pcre2 hwloc cmocka hostapd wpa_supplicant tcpdump screen iw usbutils pciutils expect aircrack-ng wireshark-cli
install_with_tmp "airgeddon" "https://raw.githubusercontent.com/v1s1t0r1sh3r3/airgeddon/refs/heads/master/airgeddon.sh" "airgeddon.sh"

# altdns
pip install py-altdns

# amap - deprecated, use nmap

# amass
go install -v github.com/owasp-amass/amass/v4/...@master

# apache-users
install_with_tmp "apache-users" "https://gitlab.com/kalilinux/packages/apache-users/-/raw/kali/master/apache2.1.pl" "apache2.1.pl"

# feroxbuster
curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | bash -s $HOME/.local/bin

# sipvicious-ng (replaces ace-voip)
echo "[*] Installing sipvicious-ng (replaces ace-voip)..."
pip install sipvicious
echo "[✓] Installed sipvicious: svmap, svwar, svcrack, svcrash"
